### ISSUE TITLE
"invalid syntax" when trying to download.

### ISSUE THREAD

**Issue by whatsupimr** [KraXen72/shira#6]
![Capture](https://github.com/KraXen72/shira/assets/23161744/a3c59865-abf4-481c-9b62-ad79f06b70d4)

Please help me. I don't know what I'm doing wrong to cause this invalid syntax. I have ffmpeg installed, as well as python 3.8. I've installed the pip-install typing-extensions too. I have other projects that use 3.8 and I don't want to break them. I'm kinda new to using GitHub projects so please forgive me :,)

**Comment by KraXen72** [comment]
Hi! thanks for making the issue.
i'm using match case (pattern matching) is only supported from python 3.10, and the project says it requires python 3.11 at least.
that's what the error is about.
try installing python 3.11 with [scoop](https://scoop.sh/#/), a package manager for windows. the link tells you how to install it and then the srcreenshot tells you want to run to install python 3.11.
![image](https://github.com/KraXen72/shira/assets/21956756/9d959c89-11ca-4bbf-af11-4ebe6453183e)

after that you can use `python311 -m shiradl`
since i've seen this issue pop up a few times already, i'll see if i can lower the lowers required version to 3.8. no promises on when that update is going to come out though.
